# numpy基础学习

## 基础矩阵

In [28]:
import numpy as np

In [29]:
matrix = np.array([1, 2, 3, 4, 5])

np.array([
    [1, 2, 3],
    [4, 5, 6, ],
    [7, 8, 9]
])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 矩阵的属性

In [30]:
matrix = np.array([1, 2, 3, 4, 5])

print(matrix.dtype)  # 类型
print(matrix.shape)  # 形状(2，5，2)：3维数组，5行，2列
print(matrix.ndim)  # 维度
print(matrix.size)  # 元素个数

int64
(5,)
1
5


## 内置的数组创建方法

### 0矩阵
> 同理还有ones，empty，full(需要指定填充的值)

In [31]:
# 0矩阵
np.zeros(5)
# 指定数组类型
np.zeros((5, 5), dtype=np.int32)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

## 常见函数

### arange() 函数
> 通过指定起始值、终止值于步长来创建一维数组,步长默认为1。
> 
> 创建的数组中**不包含**中止值

In [32]:
np.arange(1, 10, 2)
np.arange(10, 0, -3)

array([10,  7,  4,  1])

### linspace() 函数
> 通过指定起始值、终止值、元素个数来创建一维数组，步长默认为1。
> 
> 特点是默认情况下**包含**终止值，与arange()函数不同

In [33]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

### logspace() 函数
> 与linspace()函数类似，起始值、默认值默认为10的幂，不过是等比数列

In [34]:
np.logspace(1, 5, 5)

array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05])

### eye() 函数
> 生成对角线元素为1，其他元素为0的数组，类似于对角矩阵。
> 
> k – 对角线的索引：0（默认）指主对角线，正值指上对角线，负值指下对角线

In [35]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
np.eye(5, 5, k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

### diag() 函数                             
> 与eye()函数类似，可以指定对角线中的元素，可以是0或其他值。         
>                                        
> k – 对角线的索引：0（默认）指主对角线，正值指上对角线，负值指下对角线  

In [37]:
np.diag([1, 2, 3, 4, 5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [38]:
np.diag([1, 2, 3, 4, 5], k=1)

array([[0, 1, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 5],
       [0, 0, 0, 0, 0, 0]])

### random 随机数系列函数
> - rand()    
> - randint() 
> - random()  

#### rand() 函数
> 用于生成一个任意纬度的数组，元素范围默认为0-1
> Random values in a given shape.
> 
> ![](./assets/img.png)
> 参数说明：
>
> 

In [39]:
np.random.rand()

0.8259436141698852

In [40]:
np.random.rand(5, 5)

array([[0.59574821, 0.45633496, 0.50749983, 0.55560514, 0.6020559 ],
       [0.28627274, 0.89557563, 0.61621858, 0.8894139 , 0.89132706],
       [0.76602812, 0.32530778, 0.19708223, 0.41715899, 0.12740295],
       [0.11033072, 0.21288816, 0.02981182, 0.00865971, 0.58857725],
       [0.17947567, 0.3466807 , 0.96531907, 0.4193936 , 0.62235699]])

In [41]:
np.random.rand(3, 2, 1)

array([[[0.55224205],
        [0.71981537]],

       [[0.64430999],
        [0.73916865]],

       [[0.6424043 ],
        [0.75533595]]])

#### randint() 函数
> 生成指定范围的随机数 
> 
> 参数说明：
> 
> a：随机数的下限
> b：随机数的上限
> size：生成的随机数的个数

In [42]:
np.random.randint(1, 10, 5)

array([9, 7, 2, 8, 2])