# numpy基础学习

## 基础矩阵

In [28]:
import numpy as np

In [29]:
matrix = np.array([1, 2, 3, 4, 5])

np.array([
    [1, 2, 3],
    [4, 5, 6, ],
    [7, 8, 9]
])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 矩阵的属性

In [30]:
matrix = np.array([1, 2, 3, 4, 5])

print(matrix.dtype)  # 类型
print(matrix.shape)  # 形状(2，5，2)：3维数组，5行，2列
print(matrix.ndim)  # 维度
print(matrix.size)  # 元素个数

int64
(5,)
1
5


## 内置的数组创建方法

### 0矩阵
> 同理还有ones，empty，full(需要指定填充的值)

In [31]:
# 0矩阵
np.zeros(5)
# 指定数组类型
np.zeros((5, 5), dtype=np.int32)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

## 常见函数

### arange() 函数
> 通过指定起始值、终止值于步长来创建一维数组,步长默认为1。
> 
> 创建的数组中**不包含**中止值

In [32]:
np.arange(1, 10, 2)
np.arange(10, 0, -3)

array([10,  7,  4,  1])

### linspace() 函数
> 通过指定起始值、终止值、元素个数来创建一维数组，步长默认为1。
> 
> 特点是默认情况下**包含**终止值，与arange()函数不同

In [33]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

### logspace() 函数
> 与linspace()函数类似，起始值、默认值默认为10的幂，不过是等比数列

In [34]:
np.logspace(1, 5, 5)

array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05])

### eye() 函数
> 生成对角线元素为1，其他元素为0的数组，类似于对角矩阵。
> 
> k – 对角线的索引：0（默认）指主对角线，正值指上对角线，负值指下对角线

In [35]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
np.eye(5, 5, k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

### diag() 函数                             
> 与eye()函数类似，可以指定对角线中的元素，可以是0或其他值。         
>                                        
> k – 对角线的索引：0（默认）指主对角线，正值指上对角线，负值指下对角线  

In [37]:
np.diag([1, 2, 3, 4, 5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [38]:
np.diag([1, 2, 3, 4, 5], k=1)

array([[0, 1, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 5],
       [0, 0, 0, 0, 0, 0]])

### random 随机数系列函数
> - rand()    
> - randint() 
> - random()  

#### rand() 函数
> 用于生成一个任意纬度的数组，元素范围默认为0-1
> Random values in a given shape.
> 
> ![](./assets/img.png)

In [39]:
np.random.rand()

0.8259436141698852

In [40]:
np.random.rand(5, 5)

array([[0.59574821, 0.45633496, 0.50749983, 0.55560514, 0.6020559 ],
       [0.28627274, 0.89557563, 0.61621858, 0.8894139 , 0.89132706],
       [0.76602812, 0.32530778, 0.19708223, 0.41715899, 0.12740295],
       [0.11033072, 0.21288816, 0.02981182, 0.00865971, 0.58857725],
       [0.17947567, 0.3466807 , 0.96531907, 0.4193936 , 0.62235699]])

In [41]:
np.random.rand(3, 2, 1)

array([[[0.55224205],
        [0.71981537]],

       [[0.64430999],
        [0.73916865]],

       [[0.6424043 ],
        [0.75533595]]])

#### randint() 函数
> 生成指定范围的随机数 
> 
> randint(low, high=None, size=None, dtype=int)
> 参数说明：
> 
> low：随机数的下限（低位包含）
> high：随机数的上限（高位不包含）
> size：生成的随机数的个数（size可以是元祖类型的形状）

In [42]:
np.random.randint(1, 10, 5)

array([9, 7, 2, 8, 2])

In [47]:
np.random.randint(1, 10, (2, 3, 4))

array([[[4, 4, 9, 4],
        [7, 5, 2, 5],
        [1, 7, 9, 3]],

       [[2, 2, 2, 4],
        [2, 4, 1, 2],
        [9, 1, 2, 5]]])

#### random() 函数
> 生成0-1之间的随机浮点数数组，也可以给定形状
> 
> 参数说明：
> 
> size：生成的随机数的个数（size可以是元祖类型的形状）
> 一个数字是个数
> 元祖类型是形状

In [48]:
np.random.random(5)

array([0.85821925, 0.23245002, 0.17221818, 0.57642173, 0.55987104])

In [51]:
np.random.random((2, 3, 4))

array([[[0.81258786, 0.05868512, 0.52032849, 0.2337052 ],
        [0.41856559, 0.57176277, 0.69243859, 0.6131041 ],
        [0.12925353, 0.2966594 , 0.8998512 , 0.76730777]],

       [[0.2783441 , 0.11886645, 0.28983323, 0.87025189],
        [0.97039598, 0.41784996, 0.56963091, 0.60663565],
        [0.38917098, 0.47245497, 0.62336096, 0.94210062]]])

## 切片和索引

In [56]:
matrix = np.array([1, 2, 3, 4, 5])

### 简单的切片

In [61]:
matrix[:3]

array([1, 2, 3])

In [63]:
matrix[3:]

array([4, 5])

In [60]:
matrix[1:3]

array([2, 3])

In [65]:
matrix[1:5:2]

array([2, 4])

In [66]:
matrix[::-1]

array([5, 4, 3, 2, 1])

In [67]:
matrix[-1]

np.int64(5)

### 二维切片操作

In [70]:
matrix = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20]
])

In [71]:
matrix[:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [72]:
matrix[:, 1]

array([ 2,  7, 12, 17])

In [73]:
matrix[:2, :2]

array([[1, 2],
       [6, 7]])

In [74]:
matrix[1:3, 1:3]

array([[ 7,  8],
       [12, 13]])

In [78]:
matrix = np.random.random((3, 2, 3))
matrix

array([[[0.54824383, 0.57026978, 0.8199125 ],
        [0.95408817, 0.42311697, 0.32299094]],

       [[0.54024591, 0.73659926, 0.45771397],
        [0.57984313, 0.91693182, 0.66243205]],

       [[0.41274245, 0.94598796, 0.54254191],
        [0.73933191, 0.22388443, 0.72607318]]])

In [87]:
matrix[0, 1, 1]

np.float64(0.4231169743556704)

In [91]:
matrix[:2, -2, 1:]

array([[0.57026978, 0.8199125 ],
       [0.73659926, 0.45771397]])

## 修改数组形状

### reshape() 函数
> 不改变数据的条件下修改数组的形状，如果修改后的形状不符合原数组的形状，则会报错

In [92]:
matrix = np.random.random((3, 2, 3))
matrix

array([[[0.96228951, 0.56545538, 0.17757067],
        [0.82649423, 0.23595948, 0.58374138]],

       [[0.27432906, 0.73369861, 0.91225117],
        [0.93965583, 0.13574604, 0.20847101]],

       [[0.20342963, 0.02796754, 0.65052874],
        [0.00709741, 0.89156612, 0.99207726]]])

In [94]:
matrix.reshape(3, 6)

array([[0.96228951, 0.56545538, 0.17757067, 0.82649423, 0.23595948,
        0.58374138],
       [0.27432906, 0.73369861, 0.91225117, 0.93965583, 0.13574604,
        0.20847101],
       [0.20342963, 0.02796754, 0.65052874, 0.00709741, 0.89156612,
        0.99207726]])

In [101]:
matrix.reshape(3, 6, 1)

array([[[0.96228951],
        [0.56545538],
        [0.17757067],
        [0.82649423],
        [0.23595948],
        [0.58374138]],

       [[0.27432906],
        [0.73369861],
        [0.91225117],
        [0.93965583],
        [0.13574604],
        [0.20847101]],

       [[0.20342963],
        [0.02796754],
        [0.65052874],
        [0.00709741],
        [0.89156612],
        [0.99207726]]])

In [102]:
matrix.reshape(3, 6, 1).shape

(3, 6, 1)

### ravel() 函数
> 展平数组，将多维数组转换为一维数组
>   
> 参数说明：
> order: 顺序：C（默认）：按行，F：按列，A：按元素

In [108]:
np.random.random((3, 2, 3)).ravel()

array([0.32932642, 0.40634923, 0.59354863, 0.61569295, 0.49877526,
       0.79050813, 0.24448559, 0.96201383, 0.07944986, 0.47364069,
       0.20475471, 0.68008963, 0.55664927, 0.09045639, 0.02048138,
       0.40050942, 0.8579708 , 0.64396112])

In [106]:
np.random.random((3, 2, 3)).ravel(order='F')

array([0.92052669, 0.10228409, 0.89181007, 0.85827545, 0.66641908,
       0.36255808, 0.43583541, 0.46302137, 0.17987398, 0.96789792,
       0.04834872, 0.69837202, 0.06219736, 0.45637718, 0.84101446,
       0.5180817 , 0.07425303, 0.48908248])

## 组合数组

### hstack() vstack() 函数
> hstack() 水平(横向)堆叠数组
> vstack() 垂直(纵向)堆叠数组
>
> 注意，它们接受的参数应当是一个元祖，且元祖中的数组必须具有相同的形状

In [111]:
a = np.array([
    [1, 2],
    [3, 4]
])

b = np.array([
    [5, 6],
    [7, 8]
])

In [113]:
np.hstack((a, b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [114]:
np.vstack((b, a))

array([[5, 6],
       [7, 8],
       [1, 2],
       [3, 4]])

### concatenate() 函数
> 沿指定轴连接相同形状的两个或多个数组
> 
> numpy.concatenate((a1, a2, ...), axis=0)

In [ ]:
a = np.array([
    [1, 2],
    [3, 4]
])

b = np.array([
    [5, 6],
    [7, 8]
])

In [115]:
np.concatenate((a, b), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [116]:
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [117]:
np.concatenate((a, b), axis=None)

array([1, 2, 3, 4, 5, 6, 7, 8])